//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model1st
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Rollno { get; set; }
        public string StudentName { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public int CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
